### ISSUE TITLE
[Fix] xcuserdata 디렉토리 내의 user 파일이 계속 남아 commit이 안되는 문제

### ISSUE THREAD

**Issue by ivorrr987** [DeveloperAcademy-POSTECH/2023-MC2-A-TEAM11-HYOZA#18]
- 해당 파일은 .gitignore로 먼저 배제했어야 함.
- 에러가 계속 발생하던 순간에는 이미 git에 의해 추적되는 파일이라 .gitignore에 해당 파일 형식을 추가해도 add 시 제외되지 않음 -> 계속 문제 발생
- '해당 파일이 추적되지 않게 배제하는 작업', '.gitignore에 추가', '이미 올라간 원격 저장소에서 삭제' 세가지 작업을 수행해야 함.

**Comment by ivorrr987** [comment]
- '.gitignore'를 생성하고 https://www.toptal.com/developers/gitignore에서 swift, macOS에 대해 일반적으로 제외하는 파일 목록을 받아서 작성.
- `git rm -r --cached .`을 통해 우선 '모든 파일'을 추적하지 않는 파일로 만듬. 
  - `git rm`은 터미널 상의 명령어 `rm`과 `git add`를 더한 기능과 같습니다. 무슨 말이냐 하면 파일을 지우고 '해당 파일이 지워졌다는 사실'도 staging 상태에 올리는 것이죠. (stage는 `git add` 명령어로 추가된 파일들이 존재하는 영역입니다. commit 대기 중인 파일들이라고 이해하면 될 것 같습니다.)
  - `git rm --cached`는 실제 파일을 삭제하지는 않고 해당 파일을 Untracked 상태로 만든다는 뜻입니다. 즉 맥북에서는 파일이 남아있되 해당 파일을 git이 추적하는 것을 일단 해제한다는 뜻입니다. 이렇게 하면 (아마도) git은 현재 working directory를 빈 디렉토리로 생각하고 있을 겁니다. git의 기억을 일시적으로 삭제하는 걸로 생각하면 편할 것 같습니다.
  - `git rm -r`에서 `-r`은 'recursive'를 뜻합니다. 정확히 어떤 동작을 하는지 확인하지는 못했지만 단어 뜻으로 유추해볼때 어떤 디렉토리의 하위 파일들까지 파고들어 명령어를 적용한다는 것 같습니다.
  - 즉 `git rm -r --cached .` 명령어는 현재 디렉토리 내의 '모든' 파일들을 재귀적으로 찾아 git이 그 파일의 변화를 추적하지 않도록 변경하겠다는 의미가 됩니다.
- `git status`를 하면 git은 새로운 파일들이 추가되었다고 인식할 겁니다. 기억이 모두 삭제된 상태에서 눈 앞에 새로운 파일들이 나타나있는 것처럼 느끼는 거죠.
  - '삭제하고 다시 추가할거면 뭐하러 위의 작업을 한거지?'라는 생각을 할 수 있습니다. 하지만 이번에는 '.gitignore' 파일이 추가되었고 그곳에 적혀있는 파일 목록들은 git이 추적하지 않습니다. 우리가 제외하고자 했던 파일들은 목록에 나타나지 않는 것을 확인할 수 있습니다.
- `git add .`을 통해 모든 파일을 stage 시킵니다. 
- `git commit`을 통해 커밋합니다.
- `git push`를 통해 원격 저장소에 푸쉬하면 원격 저장소에 올리고 싶지 않던 파일들(정확히는 .gitignore 목록에 포함된 파일들)이 제거된 것을 확인할 수 있습니다.

**Comment by cutthebutter** [comment]
감사합니다!

**Comment by cutthebutter** [comment]
그런데 링크가 잘못된 것 같아요!

**Comment by cutthebutter** [comment]
https://seolhee2750.tistory.com/68 이 블로그 글도 잘 적어졌네요
